# Generated by Django 5.1.5 on 2025-02-06 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCurrentPosition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members',
                                            to='current_member_positions.group')),
                ('token',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_member_positions',
                                   to=settings.AUTH_USER_MODEL, to_field='token')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('token', 'group'), name='unique_token_group')],
            },
        ),
    ]
