# Generated by Django 5.1.5 on 2025-02-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_member_positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='password',
            field=models.CharField(default='123', max_length=128),
        ),
    ]
