# Generated by Django 5.1.7 on 2025-03-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_meet_locations', '0002_sitemembers_sites_memberslocations_sitemembers_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='date_range',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
