# Generated by Django 5.1.7 on 2025-03-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_meet_locations', '0003_sites_date_range'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sitemembers',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='unique_site_name_constraint'),
        ),
    ]
