# Generated by Django 5.1.7 on 2025-04-03 01:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_meet_locations', '0004_sitemembers_unique_site_name_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingChats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='current_meet_locations.sites')),
                ('site_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='current_meet_locations.sitemembers')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
